In [1]:
import torch
import pyro
import pyro.distributions as dist
from pyro.infer import MCMC, HMC, EmpiricalMarginal
import matplotlib.pyplot as plt

In [ ]:
dim = 3
true_mean = torch.randn(dim)
print('true_mean == ', true_mean)
true_sigma = torch.exp(torch.randn(dim))
print('true_sigma == ', true_sigma)

In [ ]:
def model():
    return pyro.sample('consi', pyro.distributions.Normal(true_mean, true_sigma))

In [ ]:
hmc_kernel = HMC(model, step_size=.001, num_steps=4)

In [ ]:
mcmc = MCMC(hmc_kernel, num_samples=10000, warmup_steps=3)

In [ ]:
mcmc.run()

In [ ]:
plt.plot(mcmc.get_samples()['consi'])

In [ ]:
mcmc.get_samples()['consi'].size()

In [ ]:
a = (torch.ones(3),)

In [ ]:
a.append(a)

In [ ]:
xv, yv = torch.meshgrid(torch.linspace(0, 1, 16), torch.linspace(0, 1, 16))

In [ ]:
xv

In [10]:
feat = [torch.mean, torch.exp, lambda x: 1.0]

In [11]:
feat

[<function _VariableFunctions.mean>,
 <function _VariableFunctions.exp>,
 <function __main__.<lambda>(x)>]

In [14]:
x = torch.rand(10, 7)

In [13]:
for f in feat:
    print(f(x))

tensor(0.5626)
tensor([1.5998, 1.1678, 1.3556, 2.1187, 1.5998, 1.5562, 1.2079, 2.6070, 2.4890,
        2.6518])
1


In [15]:
len(x)

10

In [22]:
x = torch.zeros(4, dtype=torch.bool)

In [23]:
x[2] = True

In [24]:
x

tensor([False, False,  True, False])

In [21]:
z

[tensor([ True, False, False, False]),
 tensor([ True, False, False, False]),
 tensor([ True, False, False, False]),
 tensor([ True, False, False, False]),
 tensor([ True, False, False, False])]